[package]
name = "ore-desktop-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
bevy-inspector-egui = "0.24.0"
# Using cocoon 0.3.1 because solana-sdk dependency curve25519-dalek has pinned zeroize version >=1 to <1.4, where cocoon 0.3.2 and after use zeroize >1.5
cocoon = "=0.3.1"
copypasta = "0.10.1"
serde = "1.0.199"
ore = { version = "1.2.1", package = "ore-program" }
solana-client = "1.18.12"
solana-sdk = "1.18.12"
spl-associated-token-account = { version = "^2.2", features = [ "no-entrypoint" ] }
toml = "0.8.12"
